-- Application rate limiting, stored in Postgres so every server instance shares the same counters.
--
-- Fixed-window counters: one row per (bucket, subject, window). Each call is a single atomic upsert.
-- Limits are data (rate_limit_policies) and can be tuned without a deploy.
--
--   user buckets    subject is always auth.uid(), taken from the verified JWT; callers can't choose it.
--   public buckets  subject is supplied by the server (a salted hash of the client IP, or of a share token).
--
-- Exceeding a limit raises SQLSTATE PT429, which PostgREST returns as HTTP 429.

create table public.rate_limit_policies (
  bucket text primary key check (bucket ~ '^[a-z_]{1,40}$'),
  max_hits integer not null check (max_hits > 0),
  window_seconds integer not null check (window_seconds between 1 and 86400),
  scope text not null check (scope in ('user', 'public')),
  description text not null default ''
);

create table public.rate_limit_counters (
  bucket text not null references public.rate_limit_policies (bucket) on delete cascade,
  subject text not null check (char_length(subject) between 1 and 128),
  window_start timestamptz not null,
  hits integer not null default 0,
  primary key (bucket, subject, window_start)
);
create index rate_limit_counters_window_idx on public.rate_limit_counters (window_start);

-- Only the functions below touch these tables.
alter table public.rate_limit_policies enable row level security;
alter table public.rate_limit_counters enable row level security;
revoke all on public.rate_limit_policies, public.rate_limit_counters from public, anon, authenticated;

insert into public.rate_limit_policies (bucket, max_hits, window_seconds, scope, description) values
  ('dataset_upload_start', 30, 3600, 'user', 'Dataset records created (upload initialisation), per user per hour. Enforced by a trigger, so direct API calls count too.'),
  ('dataset_process', 30, 3600, 'user', 'Dataset profiling and loading (upload completion, "Prepare for charts"), per user per hour.'),
  ('workspace_create', 5, 3600, 'user', 'Workspaces created with create_workspace(), per user per hour.'),
  ('report_render', 120, 600, 'user', 'Reports rendered with live chart results (viewing, creating or refreshing share links), per user per 10 minutes.'),
  ('report_pdf', 20, 600, 'user', 'Report PDFs generated by signed-in users, per user per 10 minutes.'),
  ('share_pdf_ip', 20, 600, 'public', 'Shared-report PDFs per client IP (salted hash) per 10 minutes.'),
  ('share_pdf_link', 100, 3600, 'public', 'Shared-report PDFs per share link per hour.'),
  ('ai_request', 6, 60, 'user', 'AI questions per user per minute (in addition to AI_MAX_QUESTIONS_PER_HOUR).');

-- Records one hit and reports whether it is within the limit.
create or replace function public.consume_rate_limit(p_bucket text, p_subject text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  pol public.rate_limit_policies;
  v_subject text;
  v_start timestamptz;
  v_hits integer;
begin
  select * into pol from public.rate_limit_policies where bucket = p_bucket;
  if not found then
    raise exception 'Unknown rate limit bucket' using errcode = '22023';
  end if;
  if pol.scope = 'user' then
    if auth.uid() is null then
      raise exception 'Sign in required' using errcode = '42501';
    end if;
    v_subject := auth.uid()::text;
  else
    if p_subject is null or p_subject !~ '^[A-Za-z0-9:_-]{1,128}$' then
      raise exception 'Invalid rate limit subject' using errcode = '22023';
    end if;
    v_subject := p_subject;
  end if;

  v_start := to_timestamp(floor(extract(epoch from now()) / pol.window_seconds) * pol.window_seconds);
  insert into public.rate_limit_counters as c (bucket, subject, window_start, hits)
  values (p_bucket, v_subject, v_start, 1)
  on conflict (bucket, subject, window_start) do update set hits = c.hits + 1
  returning c.hits into v_hits;

  return jsonb_build_object(
    'allowed', v_hits <= pol.max_hits,
    'limit', pol.max_hits,
    'remaining', greatest(pol.max_hits - v_hits, 0),
    'retry_after', case when v_hits <= pol.max_hits then 0
      else greatest(1, ceil(extract(epoch from (v_start + make_interval(secs => pol.window_seconds) - now())))::int) end
  );
end;
$$;

-- For use inside other database functions and triggers: raises PT429 when over the limit.
create or replace function public.enforce_rate_limit(p_bucket text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  r jsonb;
begin
  r := public.consume_rate_limit(p_bucket);
  if not (r ->> 'allowed')::boolean then
    raise exception 'Too many requests. Try again in % seconds.', r ->> 'retry_after'
      using errcode = 'PT429', hint = r ->> 'retry_after';
  end if;
end;
$$;

-- Workspace creation, whichever way it is called.
create or replace function public.create_workspace(workspace_name text, workspace_description text default '')
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;
  perform public.enforce_rate_limit('workspace_create');
  insert into public.workspaces (name, description, created_by)
  values (trim(workspace_name), coalesce(workspace_description, ''), auth.uid())
  returning id into new_id;
  insert into public.workspace_members (workspace_id, user_id, role)
  values (new_id, auth.uid(), 'owner');
  return new_id;
end;
$$;

-- Dataset records (upload initialisation), whichever way they are created.
create or replace function public.datasets_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null then
    perform public.enforce_rate_limit('dataset_upload_start');
  end if;
  return new;
end;
$$;
create trigger datasets_rate_limit before insert on public.datasets for each row execute function public.datasets_rate_limit();

-- Old windows are removed by the scheduled maintenance job.
create or replace function public.rate_limit_gc()
returns integer
language sql
security definer
set search_path = public
as $$
  with deleted as (
    delete from public.rate_limit_counters c
    using public.rate_limit_policies p
    where p.bucket = c.bucket and c.window_start < now() - make_interval(secs => p.window_seconds * 2)
    returning 1
  )
  select count(*)::integer from deleted;
$$;

revoke execute on function public.consume_rate_limit(text, text) from public;
grant execute on function public.consume_rate_limit(text, text) to anon, authenticated;
revoke execute on function public.enforce_rate_limit(text) from public, anon, authenticated;
revoke execute on function public.datasets_rate_limit() from public, anon, authenticated;
revoke execute on function public.rate_limit_gc() from public, anon, authenticated;
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.rate_limit_gc() to service_role';
  end if;
end;
$$;
