-- Security hardening from the production audit (see PRODUCTION_AUDIT.md).
-- Least-privilege grants, function execution rights, fixed search paths, tighter write rules.

-- ---------------------------------------------------------------------------
-- 1. Table privileges. Supabase grants ALL (including TRUNCATE, which ignores RLS) to anon and
--    authenticated by default. anon needs nothing here; authenticated needs only what policies allow.
-- ---------------------------------------------------------------------------
revoke all on all tables in schema public from anon;
revoke truncate, references, trigger on all tables in schema public from authenticated;
alter default privileges in schema public revoke all on tables from anon;
alter default privileges in schema public revoke truncate, references, trigger on tables from authenticated;
alter default privileges in schema public revoke execute on functions from public, anon;

-- Profiles are created by the signup trigger; users may change only their display fields.
revoke insert, update, delete on public.profiles from authenticated;
grant update (full_name, job_title, avatar_url) on public.profiles to authenticated;

-- Workspaces are created through create_workspace(); membership only by workspace creation for now
-- (no invitation flow yet). Owners/admins could otherwise add any user id without consent.
revoke insert on public.workspaces from authenticated;
drop policy if exists "members: owners and admins add" on public.workspace_members;
revoke insert on public.workspace_members from authenticated;

-- Append-only / insert-only tables.
revoke update, delete on public.ai_requests from authenticated;
revoke update on public.dataset_rows from authenticated;

-- ---------------------------------------------------------------------------
-- 2. Function execution. Nothing is executable by anon except get_shared_report().
--    Trigger functions need no EXECUTE grant to fire.
-- ---------------------------------------------------------------------------
do $$
declare
  f record;
begin
  for f in
    select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public'
  loop
    execute format('revoke execute on function %s from public, anon', f.sig);
  end loop;
end;
$$;

-- Used inside RLS policies and by the app as the signed-in user.
grant execute on function public.is_workspace_member(uuid) to authenticated;
grant execute on function public.has_workspace_role(uuid, public.workspace_role[]) to authenticated;
grant execute on function public.can_edit_workspace(uuid) to authenticated;
grant execute on function public.shares_workspace_with(uuid) to authenticated;
grant execute on function public.create_workspace(text, text) to authenticated;
grant execute on function public.query_dataset(uuid, jsonb) to authenticated;
grant execute on function public.workspace_slug(text) to authenticated;
-- The only public entry point.
grant execute on function public.get_shared_report(text) to anon, authenticated;
-- Trigger-only functions: no direct callers.
revoke execute on function public.set_updated_at() from authenticated;
revoke execute on function public.set_workspace_slug() from authenticated;
revoke execute on function public.prevent_workspace_change() from authenticated;
revoke execute on function public.validate_dashboard_layout() from authenticated;
revoke execute on function public.check_share_resource() from authenticated;
revoke execute on function public.delete_empty_workspace() from authenticated;

-- ---------------------------------------------------------------------------
-- 3. Fixed search_path on every function (prevents search-path hijacking).
-- ---------------------------------------------------------------------------
alter function public.set_updated_at() set search_path = public;
alter function public.set_workspace_slug() set search_path = public;
alter function public.prevent_workspace_change() set search_path = public;
alter function public.workspace_slug(text) set search_path = public;

-- ---------------------------------------------------------------------------
-- 4. Integrity rules.
-- ---------------------------------------------------------------------------
-- Share tokens are generated by the database and can't be replaced with a guessable value.
create or replace function public.protect_share_token()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.token is distinct from old.token then
    raise exception 'Share tokens cannot be changed' using errcode = '22023';
  end if;
  if new.created_at is distinct from old.created_at then
    raise exception 'created_at cannot be changed' using errcode = '22023';
  end if;
  return new;
end;
$$;
create trigger shares_protect_token before update on public.shares for each row execute function public.protect_share_token();
revoke execute on function public.protect_share_token() from public, anon, authenticated;

-- created_by always records the signed-in user and can't be rewritten.
create or replace function public.stamp_created_by()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    if auth.uid() is not null then
      new.created_by := auth.uid();
    end if;
  elsif new.created_by is distinct from old.created_by then
    new.created_by := old.created_by;
  end if;
  return new;
end;
$$;
revoke execute on function public.stamp_created_by() from public, anon, authenticated;
do $$
declare
  t text;
begin
  foreach t in array array['datasets', 'projects', 'visualizations', 'dashboards', 'reports', 'shares'] loop
    execute format('create trigger %1$s_stamp_created_by before insert or update on public.%1$I for each row execute function public.stamp_created_by()', t);
  end loop;
end;
$$;

-- References must stay inside one workspace.
alter table public.projects add constraint projects_id_workspace_key unique (id, workspace_id);
alter table public.visualizations drop constraint if exists visualizations_project_id_fkey;
alter table public.visualizations
  add constraint visualizations_project_same_workspace
  foreign key (project_id, workspace_id) references public.projects (id, workspace_id) on delete set null (project_id);
alter table public.reports drop constraint if exists reports_project_id_fkey;
alter table public.reports
  add constraint reports_project_same_workspace
  foreign key (project_id, workspace_id) references public.projects (id, workspace_id) on delete set null (project_id);
alter table public.ai_requests drop constraint if exists ai_requests_dataset_id_fkey;
alter table public.ai_requests
  add constraint ai_requests_dataset_same_workspace
  foreign key (dataset_id, workspace_id) references public.datasets (id, workspace_id) on delete set null (dataset_id);

-- ---------------------------------------------------------------------------
-- 5. query_dataset: same behaviour, with input limits.
-- ---------------------------------------------------------------------------
create or replace function public.query_dataset(p_dataset uuid, p_spec jsonb)
returns jsonb
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  col_types jsonb;
  x_col int; x_type text; x_grain text; x_expr text; x_order text;
  y_col int; y_type text; y_agg text; y_expr text;
  s_col int; s_type text; s_expr text := 'null::text';
  f jsonb; f_col int; f_type text; f_op text; f_val jsonb; cell text;
  conds text[] := array[]::text[];
  where_sql text;
  lim int := least(greatest(coalesce((p_spec ->> 'limit')::int, 50), 1), 500);
  max_series constant int := 8;
  x_is_category boolean;
  result jsonb;
begin
  -- Input limits (defence against oversized specs).
  if p_spec is null or jsonb_typeof(p_spec) <> 'object' then
    raise exception 'Invalid chart definition' using errcode = '22023';
  end if;
  if p_spec ? 'filters' and jsonb_typeof(p_spec -> 'filters') <> 'array' then
    raise exception 'Invalid filters' using errcode = '22023';
  end if;
  if jsonb_array_length(coalesce(p_spec -> 'filters', '[]'::jsonb)) > 20 then
    raise exception 'Use at most 20 filters' using errcode = '22023';
  end if;
  if not exists (select 1 from datasets where id = p_dataset) then
    raise exception 'Dataset not found' using errcode = 'PT404'; -- PostgREST returns HTTP 404 for PT404
  end if;
  select coalesce(jsonb_object_agg(position::text, data_type), '{}'::jsonb) into col_types
  from dataset_columns where dataset_id = p_dataset;

  conds := conds || format('r.dataset_id = %L', p_dataset);

  -- Measure
  y_agg := coalesce(p_spec #>> '{y,agg}', 'count');
  if y_agg not in ('count', 'count_distinct', 'sum', 'avg', 'min', 'max') then
    raise exception 'Unsupported aggregation: %', y_agg using errcode = '22023';
  end if;
  if y_agg = 'count' then
    y_expr := 'count(*)';
  else
    y_col := (p_spec #>> '{y,col}')::int;
    y_type := col_types ->> y_col::text;
    if y_type is null then raise exception 'Unknown measure column' using errcode = '22023'; end if;
    if y_agg = 'count_distinct' then
      y_expr := format('count(distinct r.cells ->> %s)', y_col);
    elsif y_type in ('integer', 'decimal', 'currency', 'percent') then
      y_expr := format('%s((r.cells ->> %s)::numeric)', y_agg, y_col);
    else
      raise exception 'Only number columns can be summed or averaged' using errcode = '22023';
    end if;
  end if;

  -- Filters
  for f in select * from jsonb_array_elements(coalesce(p_spec -> 'filters', '[]'::jsonb)) loop
    f_col := (f ->> 'col')::int;
    f_type := col_types ->> f_col::text;
    f_op := f ->> 'op';
    f_val := f -> 'value';
    if f_type is null then raise exception 'Unknown filter column' using errcode = '22023'; end if;
    if f_op in ('in', 'not_in') and (jsonb_typeof(f_val) <> 'array' or jsonb_array_length(f_val) > 500) then
      raise exception 'List filters need between 1 and 500 values' using errcode = '22023';
    end if;
    if f_val is not null and jsonb_typeof(f_val) not in ('array', 'string', 'number', 'boolean', 'null') then
      raise exception 'Invalid filter value' using errcode = '22023';
    end if;
    cell := format('(r.cells ->> %s)', f_col);
    conds := conds || case
      when f_op = 'empty' then format('%s is null', cell)
      when f_op = 'not_empty' then format('%s is not null', cell)
      when f_op in ('in', 'not_in') then
        format('%s %s any(%L::text[])', cell, case when f_op = 'in' then '=' else '<>' end,
          (select coalesce(array_agg(v), '{}') from jsonb_array_elements_text(f_val) v))
      when f_type in ('integer', 'decimal', 'currency', 'percent') and f_op in ('eq', 'neq', 'gt', 'gte', 'lt', 'lte') then
        format('(%s)::numeric %s %L::numeric', cell,
          case f_op when 'eq' then '=' when 'neq' then '<>' when 'gt' then '>' when 'gte' then '>=' when 'lt' then '<' else '<=' end,
          f_val #>> '{}')
      when f_type = 'date' and f_op in ('eq', 'gt', 'gte', 'lt', 'lte') then
        format('(%s)::timestamp %s %L::timestamp', cell,
          case f_op when 'eq' then '=' when 'gt' then '>' when 'gte' then '>=' when 'lt' then '<' else '<=' end,
          f_val #>> '{}')
      when f_op in ('eq', 'neq') then
        format('%s is %s distinct from %L', cell, case when f_op = 'eq' then 'not' else '' end, f_val #>> '{}')
      when f_op = 'contains' then
        format('%s ilike %L', cell, '%' || replace(replace(replace(f_val #>> '{}', '\', '\\'), '%', '\%'), '_', '\_') || '%')
      else null
    end;
    if conds[array_length(conds, 1)] is null then
      raise exception 'Unsupported filter "%" for a % column', f_op, f_type using errcode = '22023';
    end if;
  end loop;

  -- Date range
  if p_spec -> 'range' is not null and jsonb_typeof(p_spec -> 'range') = 'object' then
    f_col := (p_spec #>> '{range,col}')::int;
    if col_types ->> f_col::text is distinct from 'date' then
      raise exception 'Date ranges need a date column' using errcode = '22023';
    end if;
    if p_spec #>> '{range,from}' is not null then
      conds := conds || format('(r.cells ->> %s)::timestamp >= %L::timestamp', f_col, p_spec #>> '{range,from}');
    end if;
    if p_spec #>> '{range,to}' is not null then
      conds := conds || format('(r.cells ->> %s)::timestamp < (%L::date + 1)::timestamp', f_col, p_spec #>> '{range,to}');
    end if;
  end if;

  where_sql := array_to_string(conds, ' and ');

  -- Grouping column (none for a single KPI value)
  if p_spec -> 'x' is null or jsonb_typeof(p_spec -> 'x') <> 'object' then
    execute format(
      'select jsonb_build_object(''rows'', jsonb_build_array(jsonb_build_object(''x'', null, ''s'', null, ''v'', %1$s)), ''total'', %1$s, ''matched'', count(*), ''truncated_x'', false, ''truncated_series'', false) from dataset_rows r where %2$s',
      y_expr, where_sql)
    into result;
    return result;
  end if;

  x_col := (p_spec #>> '{x,col}')::int;
  x_type := col_types ->> x_col::text;
  if x_type is null then raise exception 'Unknown x-axis column' using errcode = '22023'; end if;
  x_grain := coalesce(p_spec #>> '{x,grain}', 'month');
  if x_type = 'date' then
    if x_grain not in ('day', 'week', 'month', 'quarter', 'year') then
      raise exception 'Unsupported date grain: %', x_grain using errcode = '22023';
    end if;
    x_expr := format('to_char(date_trunc(%L, (r.cells ->> %s)::timestamp), ''YYYY-MM-DD'')', x_grain, x_col);
    x_order := 'x';
    x_is_category := false;
    conds := conds || format('(r.cells ->> %s) is not null', x_col);
  elsif x_type in ('integer', 'decimal', 'currency', 'percent') then
    x_expr := format('(r.cells ->> %s)', x_col);
    x_order := 'x::numeric';
    x_is_category := false;
    conds := conds || format('(r.cells ->> %s) is not null', x_col);
  else
    x_expr := format('coalesce(r.cells ->> %s, ''(empty)'')', x_col);
    x_order := 'v desc nulls last, x';
    x_is_category := true;
  end if;
  where_sql := array_to_string(conds, ' and ');

  if p_spec -> 'series' is not null and jsonb_typeof(p_spec -> 'series') = 'object' then
    s_col := (p_spec #>> '{series,col}')::int;
    s_type := col_types ->> s_col::text;
    if s_type is null or s_type not in ('text', 'boolean') then
      raise exception 'Series can only be split by a text or yes/no column' using errcode = '22023';
    end if;
    s_expr := format('coalesce(r.cells ->> %s, ''(empty)'')', s_col);
  end if;

  -- One pass over the rows: GROUPING SETS returns every (x, series) group plus the grand total row.
  execute format($q$
    with scanned as (
      select grouping(%1$s, %2$s) as is_total, %1$s as x, %2$s as s, %3$s as v, count(*) as n
      from dataset_rows r where %4$s
      group by grouping sets ((%1$s, %2$s), ())
    ),
    grouped as (select x, s, v from scanned where is_total = 0),
    x_totals as (select x, %5$s as v from grouped group by x),
    top_x as (select x from x_totals order by %6$s limit %7$s),
    s_totals as (select s, %5$s as v from grouped group by s),
    top_s as (select s from s_totals order by v desc nulls last, s limit %8$s)
    select jsonb_build_object(
      'rows', coalesce((
        select jsonb_agg(jsonb_build_object('x', g.x, 's', g.s, 'v', g.v) order by g.x, g.s)
        from grouped g
        where g.x in (select x from top_x) and (g.s is null or g.s in (select s from top_s))
      ), '[]'::jsonb),
      'total', (select v from scanned where is_total <> 0),
      'matched', coalesce((select n from scanned where is_total <> 0), 0),
      'truncated_x', (select count(*) from x_totals) > %7$s,
      'truncated_series', (select count(*) from s_totals where s is not null) > %8$s
    )
  $q$,
    x_expr, s_expr, y_expr, where_sql,
    -- Combining groups: counts and sums add up; for other aggregations the largest group decides the order.
    case when y_agg in ('count', 'count_distinct', 'sum') then 'sum(v)' when y_agg = 'min' then 'min(v)' else 'max(v)' end,
    case when x_is_category then 'v desc nulls last, x' else x_order end,
    case when x_is_category then lim else 1000 end,
    max_series)
  into result;
  return result;
end;
$$;

revoke execute on function public.query_dataset(uuid, jsonb) from public, anon;
grant execute on function public.query_dataset(uuid, jsonb) to authenticated;
